name: aws-eks-deploy

on:
  #push:
  workflow_dispatch:

env:
  KUBECONFIG: ${HOME}/.kube/config
  NAMESPACE: ingress-basic
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository:  'ParisaMousavi/aws-eks'

      - name: Install aws cli
        run: |
          aws --version
          export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION=${{secrets.AWS_DEFAULT_REGION}}
          aws configure


