name: aws-eks-deploy

on:
  #push:
  workflow_dispatch:

env:
  KUBECONFIG: ${HOME}/.kube/config
  NAMESPACE: ingress-basic
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository:  'ParisaMousavi/aws-eks'

      - name: Install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version


