name: az-aks-workload-identity-sample

on:
  #push:
  workflow_dispatch:

env:
  KUBECONFIG: ${HOME}/.kube/config
  NAMESPACE: ingress-basic
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          # Repository name with owner. For example, actions/checkout
          repository:  'ParisaMousavi/solution-11-aks-apps'
    
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Display Azure account info
        run: az account show -o json
        
      - name: Get AKS Kube Config
        run: az aks get-credentials --overwrite-existing --resource-group ${{ secrets.aks_cluster_resourcegroup_name }} --name ${{ secrets.aks_cluster_name }} --file $KUBECONFIG

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
           kubelogin-version: 'v0.0.24'
           
      - name: login with kubelogin
        run: kubelogin convert-kubeconfig -l spn --client-id ${{ secrets.ARM_CLIENT_ID }} --client-secret ${{ secrets.ARM_CLIENT_SECRET }}     
     
      - name: verify the nodes
        run: kubectl get node
        
      - name: deploy quick-start
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        env:
          KEYVAULT_URL: ${{ secrets.KEYVAULT_URL }}
          NAMESPACE: ${{ secrets.Workload_Identity_Sample_Namespace }}
        with:
          k8-config-file-paths: |
            az-aks-workload-identity-sample/az-aks-workload-identity-sample.yaml
