name: azure-fabric-deploy

on:
  #push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  greet:
    runs-on: ubuntu-latest
    environment: azure-fabric-deploy

    defaults:
     run:
      shell: bash
      working-directory: ./az-fabric

    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        with:
          # Repository name with owner. For example, actions/checkout
          repository:  'ParisaMousavi/az-fabric'

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
           
      - name:  terraform init
        run: |
          terraform init

      - name:  terraform plan
        run: |
          terraform plan \
          -var connect_to_arc=${{ vars.CONNECT_TO_ARC }} \
          -var install_arc_monitor=${{ vars.INSTALL_ARC_MONITOR }} 
          
      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        run: terraform apply        
          
          
