# This is a basic workflow to help you get started with Actions

name: call reusable workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
  job_name:
    uses: ./.github/workflows/resusable-workflow.yml
    with:
      image_name: my-awesome-app
      tag: 111
    secrets:
      registry_username: edrf
      registry_password: 6578
