name: resusable-workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello 1"


  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello 2"
